server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/flowable-demo?autoReconnect=true&useSSL=false&allowMultiQueries=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: root
  aop:
    proxy-target-class: false


logging:
    level:
      root: info
      org.flowable: debug
      org.flowable.job: info
      org.flowable.common.engine.impl.db.DbSqlSession: info
      org.flowable.common.spring.SpringTransactionInterceptor: info
      org.flowable.common.engine.impl.agenda.AbstractAgenda: info
      org.flowable.common.engine.impl.interceptor.LogInterceptor: info
      org.flowable.engine.impl.interceptor.CommandInvoker: info

#flowable:
#  database-schema-update: true
#  async-executor-activate: false
